on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    name: Build Nix targets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          flake-lock-path: ./flake.lock
          check-owner: false
          ignore-missing-flake-lock: false
          fail-mode: true
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Build default package
        run: nix build
